export const dummyBooks = [
  { id: 1, title: "The Great Gatsby", author: "F. Scott Fitzgerald", category: "Fiction", description: "A classic novel set in the Jazz Age.", rating: 4.5 },
  { id: 2, title: "A Brief History of Time", author: "Stephen Hawking", category: "Non-Fiction", description: "An exploration of cosmology.", rating: 4.7 },
  { id: 3, title: "Dune", author: "Frank Herbert", category: "Sci-Fi", description: "A science fiction masterpiece.", rating: 4.6 },
  { id: 4, title: "To Kill a Mockingbird", author: "Harper Lee", category: "Fiction", description: "A story of racial injustice in the Deep South.", rating: 4.8 },
  { id: 5, title: "Sapiens", author: "Yuval Noah Harari", category: "Non-Fiction", description: "A brief history of humankind.", rating: 4.6 },
  { id: 6, title: "Neuromancer", author: "William Gibson", category: "Sci-Fi", description: "Cyberpunk classic that shaped the genre.", rating: 4.4 },
  { id: 7, title: "1984", author: "George Orwell", category: "Fiction", description: "A dystopian novel about surveillance and control.", rating: 4.9 },
  { id: 8, title: "Educated", author: "Tara Westover", category: "Non-Fiction", description: "A memoir of transformation through education.", rating: 4.7 },
  { id: 9, title: "Foundation", author: "Isaac Asimov", category: "Sci-Fi", description: "A saga of the fall and rise of civilizations.", rating: 4.5 },
  { id: 10, title: "Pride and Prejudice", author: "Jane Austen", category: "Fiction", description: "A romantic tale of manners and marriage.", rating: 4.6 },
  { id: 11, title: "The Selfish Gene", author: "Richard Dawkins", category: "Non-Fiction", description: "Evolution explained through gene-centered theory.", rating: 4.4 },
  { id: 12, title: "Snow Crash", author: "Neal Stephenson", category: "Sci-Fi", description: "A fast-paced cyberpunk adventure.", rating: 4.3 },
  { id: 13, title: "The Catcher in the Rye", author: "J.D. Salinger", category: "Fiction", description: "A teenager's journey through alienation.", rating: 4.2 },
  { id: 14, title: "Thinking, Fast and Slow", author: "Daniel Kahneman", category: "Non-Fiction", description: "Insights into human decision-making.", rating: 4.8 },
  { id: 15, title: "Ender's Game", author: "Orson Scott Card", category: "Sci-Fi", description: "A young genius trained for interstellar war.", rating: 4.7 },
  { id: 16, title: "Jane Eyre", author: "Charlotte Brontë", category: "Fiction", description: "A gothic romance of resilience and love.", rating: 4.5 },
  { id: 17, title: "The Immortal Life of Henrietta Lacks", author: "Rebecca Skloot", category: "Non-Fiction", description: "The story behind HeLa cells and medical ethics.", rating: 4.6 },
  { id: 18, title: "The Martian", author: "Andy Weir", category: "Sci-Fi", description: "A stranded astronaut's survival on Mars.", rating: 4.8 },
  { id: 19, title: "Wuthering Heights", author: "Emily Brontë", category: "Fiction", description: "A tale of passion and revenge.", rating: 4.3 },
  { id: 20, title: "Outliers", author: "Malcolm Gladwell", category: "Non-Fiction", description: "The story of success and hidden advantages.", rating: 4.5 },
  { id: 21, title: "Brave New World", author: "Aldous Huxley", category: "Sci-Fi", description: "A dystopia of engineered happiness.", rating: 4.6 },
  { id: 22, title: "Little Women", author: "Louisa May Alcott", category: "Fiction", description: "The lives of four sisters growing up.", rating: 4.4 },
  { id: 23, title: "The Power of Habit", author: "Charles Duhigg", category: "Non-Fiction", description: "How habits shape our lives.", rating: 4.7 },
  { id: 24, title: "Hyperion", author: "Dan Simmons", category: "Sci-Fi", description: "A pilgrimage through time and mystery.", rating: 4.5 },
  { id: 25, title: "The Alchemist", author: "Paulo Coelho", category: "Fiction", description: "A journey of dreams and destiny.", rating: 4.6 },
  { id: 26, title: "Guns, Germs, and Steel", author: "Jared Diamond", category: "Non-Fiction", description: "The fates of human societies explained.", rating: 4.4 },
  { id: 27, title: "Ready Player One", author: "Ernest Cline", category: "Sci-Fi", description: "A virtual reality treasure hunt.", rating: 4.3 },
  { id: 28, title: "The Book Thief", author: "Markus Zusak", category: "Fiction", description: "A story of love and loss in Nazi Germany.", rating: 4.8 },
  { id: 29, title: "The Sixth Extinction", author: "Elizabeth Kolbert", category: "Non-Fiction", description: "A look at mass extinction in our time.", rating: 4.5 },
  { id: 30, title: "Children of Time", author: "Adrian Tchaikovsky", category: "Sci-Fi", description: "Evolution and survival on a distant planet.", rating: 4.7 },
  { id: 31, title: "The Kite Runner", author: "Khaled Hosseini", category: "Fiction", description: "A story of friendship and redemption.", rating: 4.9 },
  { id: 32, title: "Quiet", author: "Susan Cain", category: "Non-Fiction", description: "The power of introverts in a noisy world.", rating: 4.6 },
  { id: 33, title: "The Left Hand of Darkness", author: "Ursula K. Le Guin", category: "Sci-Fi", description: "Exploring gender and politics on a frozen world.", rating: 4.5 },
  { id: 34, title: "The Road", author: "Cormac McCarthy", category: "Fiction", description: "A bleak journey through a post-apocalyptic world.", rating: 4.4 },
  { id: 35, title: "The Body Keeps the Score", author: "Bessel van der Kolk", category: "Non-Fiction", description: "Trauma and healing through neuroscience.", rating: 4.8 },
  { id: 36, title: "Red Mars", author: "Kim Stanley Robinson", category: "Sci-Fi", description: "Colonizing and terraforming Mars.", rating: 4.6 },
  { id: 37, title: "The Bell Jar", author: "Sylvia Plath", category: "Fiction", description: "A young woman's descent into depression.", rating: 4.3 },
  { id: 38, title: "Factfulness", author: "Hans Rosling", category: "Non-Fiction", description: "A hopeful look at global progress.", rating: 4.7 },
  { id: 39, title: "The Three-Body Problem", author: "Liu Cixin", category: "Sci-Fi", description: "First contact with an alien civilization.", rating: 4.6 },
  { id: 40, title: "The Secret Garden", author: "Frances Hodgson Burnett", category: "Fiction", description: "A magical garden transforms lives.", rating: 4.5 },
  { id: 41, title: "Why We Sleep", author: "Matthew Walker", category: "Non-Fiction", description: "The science of sleep and its impact.", rating: 4.8 },
  { id: 42, title: "Annihilation", author: "Jeff VanderMeer", category: "Sci-Fi", description: "A mysterious zone defies explanation.", rating: 4.4 },
    { id: 43, title: "Great Expectations", author: "Charles Dickens", category: "Fiction", description: "The growth and personal development of an orphan named Pip.", rating: 4.2 },
];